"""add language to entries

Revision ID: b25333219495
Revises: bf659b92c1b6
Create Date: 2018-01-25 14:14:49.826831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25333219495'
down_revision = 'bf659b92c1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'language')
    # ### end Alembic commands ###
