"""added Text Metrics for Entry and Post models

Revision ID: fd16e58f4c40
Revises: b25333219495
Create Date: 2018-01-25 18:54:58.893195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd16e58f4c40'
down_revision = 'b25333219495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('aptitude', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('attention', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('depression_factor', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('mood_tags', sa.String(), nullable=True))
    op.add_column('entry', sa.Column('pleasantness', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('polarity', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('sensitivity', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('subjectivity', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('word_semantics', sa.String(), nullable=True))
    op.add_column('post', sa.Column('aptitude', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('attention', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('depression_factor', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('mood_tags', sa.String(), nullable=True))
    op.add_column('post', sa.Column('pleasantness', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('polarity', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('sensitivity', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('subjectivity', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('word_semantics', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'word_semantics')
    op.drop_column('post', 'subjectivity')
    op.drop_column('post', 'sensitivity')
    op.drop_column('post', 'polarity')
    op.drop_column('post', 'pleasantness')
    op.drop_column('post', 'mood_tags')
    op.drop_column('post', 'depression_factor')
    op.drop_column('post', 'attention')
    op.drop_column('post', 'aptitude')
    op.drop_column('entry', 'word_semantics')
    op.drop_column('entry', 'subjectivity')
    op.drop_column('entry', 'sensitivity')
    op.drop_column('entry', 'polarity')
    op.drop_column('entry', 'pleasantness')
    op.drop_column('entry', 'mood_tags')
    op.drop_column('entry', 'depression_factor')
    op.drop_column('entry', 'attention')
    op.drop_column('entry', 'aptitude')
    # ### end Alembic commands ###
